"""empty message

Revision ID: 099656c0f717
Revises: 151165e472fe
Create Date: 2025-10-23 10:52:56.920304

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '099656c0f717'
down_revision = '151165e472fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scores', postgresql.ARRAY(sa.Float()), nullable=True))
        batch_op.drop_column('final_score')
        batch_op.drop_column('score_1')
        batch_op.drop_column('score_2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score_2', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('score_1', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('final_score', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('scores')

    # ### end Alembic commands ###
