"""empty message

Revision ID: 131488573826
Revises: 992aad2dcd00
Create Date: 2025-10-30 13:42:47.616734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '131488573826'
down_revision = '992aad2dcd00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_day', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('class_day_course_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'course', ['course_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_day', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('class_day_course_id_fkey'), 'course', ['course_id'], ['id'])

    # ### end Alembic commands ###
