"""make some changes

Revision ID: 22abaac6994d
Revises: 7fc536ea3e44
Create Date: 2025-10-20 15:11:09.569653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22abaac6994d'
down_revision = '7fc536ea3e44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('semester', schema=None) as batch_op:
        batch_op.alter_column(
            'year',
            existing_type=sa.DATE(),
            type_=sa.Integer(),
            postgresql_using="EXTRACT(YEAR FROM year)::integer",
            existing_nullable=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('semester', schema=None) as batch_op:
        batch_op.alter_column('year',
               existing_type=sa.Integer(),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
