"""empty message

Revision ID: 413627e4fcee
Revises: 131488573826
Create Date: 2025-10-30 14:37:41.930265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '413627e4fcee'
down_revision = '131488573826'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('course_teacher_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('course_subject_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'subject', ['subject_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['teacher_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('course_subject_id_fkey'), 'subject', ['subject_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('course_teacher_id_fkey'), 'user', ['teacher_id'], ['id'])

    # ### end Alembic commands ###
