"""empty message

Revision ID: 431625424a05
Revises: 9544748e2631
Create Date: 2025-10-28 12:15:36.696069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '431625424a05'
down_revision = '9544748e2631'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('extracted_face')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extracted_face', sa.NullType(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
