"""empty message

Revision ID: 4462b4a9e959
Revises: d9b57afc2af6
Create Date: 2025-10-26 14:39:51.848463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4462b4a9e959'
down_revision = 'd9b57afc2af6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_name', sa.String(length=15), nullable=True))
        batch_op.create_unique_constraint(None, ['account_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('account_name')

    # ### end Alembic commands ###
