"""make some changes

Revision ID: 58baa28eb573
Revises: 6ffb83f1ad95
Create Date: 2025-10-18 19:58:18.461920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58baa28eb573'
down_revision = '6ffb83f1ad95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('change_info_request', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('change_info_request_personal_id_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('change_info_request', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('change_info_request_personal_id_key'), ['personal_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
