"""make some changes

Revision ID: 6ffb83f1ad95
Revises: cd458e673c3b
Create Date: 2025-10-18 19:38:00.032206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ffb83f1ad95'
down_revision = 'cd458e673c3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_info_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('personal_id', sa.String(length=15), nullable=True),
    sa.Column('phone_number', sa.String(length=10), nullable=True),
    sa.Column('address', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('school_id', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['user.school_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('personal_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('change_info_request')
    # ### end Alembic commands ###
