"""empty message

Revision ID: 73714e8b1083
Revises: 431625424a05
Create Date: 2025-10-28 14:10:03.927395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73714e8b1083'
down_revision = '431625424a05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('semester', schema=None) as batch_op:
        batch_op.add_column(sa.Column('semester_id', sa.String(length=15), nullable=True))
        batch_op.create_unique_constraint(None, ['semester_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('semester', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('semester_id')

    # ### end Alembic commands ###
