"""empty message

Revision ID: 792da2b5e6d9
Revises: e592043b3084
Create Date: 2025-10-30 16:45:21.472272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '792da2b5e6d9'
down_revision = 'e592043b3084'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_day', schema=None) as batch_op:
        batch_op.alter_column('course_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=15),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_day', schema=None) as batch_op:
        batch_op.alter_column('course_id',
               existing_type=sa.String(length=15),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
