"""make some changes

Revision ID: 7fc536ea3e44
Revises: ec0e08d2656a
Create Date: 2025-10-20 14:43:57.046926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fc536ea3e44'
down_revision = 'ec0e08d2656a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.drop_column('subject_name')

    # ### end Alembic commands ###
