"""make some changes

Revision ID: 8b8f24e101fb
Revises: 22abaac6994d
Create Date: 2025-10-20 16:31:24.955404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b8f24e101fb'
down_revision = '22abaac6994d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_day', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_day', schema=None) as batch_op:
        batch_op.drop_column('day')

    # ### end Alembic commands ###
