"""empty message

Revision ID: 8bbc28ab73a9
Revises: 4462b4a9e959
Create Date: 2025-10-26 16:03:42.171285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bbc28ab73a9'
down_revision = '4462b4a9e959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('account_school_id_fkey'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('account_school_id_fkey'), 'user', ['school_id'], ['id'])

    # ### end Alembic commands ###
