"""empty message

Revision ID: 8ce9098ce928
Revises: aba8e4413fe4
Create Date: 2025-10-26 14:25:44.063202

"""
from alembic import op
import sqlalchemy as sa
import pgvector



# revision identifiers, used by Alembic.
revision = '8ce9098ce928'
down_revision = 'aba8e4413fe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('extracted_face', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True),
    sa.Column('password_hash', sa.String(length=200), nullable=True),
    sa.Column('first_login', sa.Boolean(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('face_of_student')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('face_of_student',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('extracted_face', pgvector.sqlalchemy.vector.VECTOR(dim=512), autoincrement=False, nullable=True),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('first_login', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], name=op.f('face_of_student_student_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('face_of_student_pkey'))
    )
    op.drop_table('account')
    # ### end Alembic commands ###
