"""empty message

Revision ID: 971bd95a2e44
Revises: 0116cc731771
Create Date: 2025-12-11 14:54:49.554807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '971bd95a2e44'
down_revision = '0116cc731771'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('schedule')

    # ### end Alembic commands ###
