"""empty message

Revision ID: 992aad2dcd00
Revises: 73714e8b1083
Create Date: 2025-10-29 10:31:10.348115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '992aad2dcd00'
down_revision = '73714e8b1083'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('course_semester_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'semester', ['semester_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('course_semester_id_fkey'), 'semester', ['semester_id'], ['id'])

    # ### end Alembic commands ###
