"""empty message

Revision ID: aba8e4413fe4
Revises: 099656c0f717
Create Date: 2025-10-26 14:24:45.631752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aba8e4413fe4'
down_revision = '099656c0f717'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('face_of_student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('first_login', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('first_login')
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('first_login', sa.BOOLEAN(), autoincrement=False, nullable=True))

    with op.batch_alter_table('face_of_student', schema=None) as batch_op:
        batch_op.drop_column('first_login')
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
