"""empty message

Revision ID: c2a64a4f3f25
Revises: 8bbc28ab73a9
Create Date: 2025-10-26 16:04:01.657004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2a64a4f3f25'
down_revision = '8bbc28ab73a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.alter_column('school_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=15),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.alter_column('school_id',
               existing_type=sa.String(length=15),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
