"""make some changes

Revision ID: cd458e673c3b
Revises: 13d06a5575b2
Create Date: 2025-10-18 19:37:31.898683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd458e673c3b'
down_revision = '13d06a5575b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('school_id',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('school_id',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)

    # ### end Alembic commands ###
