"""make some changes

Revision ID: d6546573cc5a
Revises: 8b8f24e101fb
Create Date: 2025-10-20 18:35:39.002430

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd6546573cc5a'
down_revision = '8b8f24e101fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('class_prior')
    with op.batch_alter_table('class_day', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prior', postgresql.ARRAY(sa.Integer()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_day', schema=None) as batch_op:
        batch_op.drop_column('prior')

    op.create_table('class_prior',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('class_day_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['class_day_id'], ['class_day.id'], name=op.f('class_prior_class_day_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('class_prior_pkey'))
    )
    # ### end Alembic commands ###
