"""empty message

Revision ID: d9b57afc2af6
Revises: 8ce9098ce928
Create Date: 2025-10-26 14:34:51.299954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9b57afc2af6'
down_revision = '8ce9098ce928'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('account_student_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['school_id'], ['id'])
        batch_op.drop_column('student_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('account_student_id_fkey'), 'user', ['student_id'], ['id'])
        batch_op.drop_column('school_id')

    # ### end Alembic commands ###
