"""empty message

Revision ID: dbe3034b97a8
Revises: 971bd95a2e44
Create Date: 2025-12-11 16:19:34.677684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbe3034b97a8'
down_revision = '971bd95a2e44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('day_off', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('day_off_class_day_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'class_day', ['class_day_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('day_off', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('day_off_class_day_id_fkey'), 'class_day', ['class_day_id'], ['id'])

    # ### end Alembic commands ###
