"""empty message

Revision ID: e592043b3084
Revises: 413627e4fcee
Create Date: 2025-10-30 16:44:53.821110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e592043b3084'
down_revision = '413627e4fcee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_day', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('class_day_course_id_fkey'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_day', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('class_day_course_id_fkey'), 'course', ['course_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###
