"""empty message

Revision ID: e81f8e3e9d77
Revises: 855c3089bf3b
Create Date: 2025-10-23 10:05:39.639643

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e81f8e3e9d77'
down_revision = '855c3089bf3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scores', postgresql.ARRAY(sa.Integer()), nullable=True))
        batch_op.add_column(sa.Column('weights', postgresql.ARRAY(sa.Integer()), nullable=True))
        batch_op.drop_column('weight_score_1')
        batch_op.drop_column('weight_score_2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight_score_2', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('weight_score_1', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('weights')
        batch_op.drop_column('scores')

    # ### end Alembic commands ###
