"""make some changes

Revision ID: ec0e08d2656a
Revises: 58baa28eb573
Create Date: 2025-10-20 13:38:39.714085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec0e08d2656a'
down_revision = '58baa28eb573'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_id', sa.String(length=15), nullable=True))
        batch_op.create_unique_constraint(None, ['subject_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('subject_id')

    # ### end Alembic commands ###
