"""empty message

Revision ID: fd39fffc6098
Revises: 792da2b5e6d9
Create Date: 2025-10-30 16:45:36.992558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd39fffc6098'
down_revision = '792da2b5e6d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_day', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'course', ['course_id'], ['course_id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_day', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
